# Generated by Django 5.0.7 on 2025-05-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeforgeuser',
            name='profile_picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='memeforgeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
