# Generated by Django 5.0.7 on 2025-05-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_memeforgeuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeforgeuser',
            name='x_account',
            field=models.CharField(max_length=50, null=True, verbose_name='X Profile'),
        ),
    ]
