# Generated by Django 5.0.7 on 2025-05-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_memeforgeuser_x_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeforgeuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memeforgeuser',
            name='x_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='X Profile'),
        ),
    ]
