# Generated by Django 5.0.7 on 2025-05-16 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0003_featured_order'),
        ('users', '0004_alter_memeforgeuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTabiPayCardOverlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username_text', models.CharField(max_length=100)),
                ('name_text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overlays', to='featured.tabipaycard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabipay_overlays', to='users.memeforgeuser')),
            ],
        ),
    ]
