# Generated by Django 5.0.7 on 2025-05-18 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usertabipaycardoverlay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertabipaycardoverlay',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabipay_overlays', to='users.memeforgeuser'),
        ),
    ]
