# Generated by Django 5.0.7 on 2025-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='image',
            field=models.ImageField(null=True, upload_to='roadmap/'),
        ),
    ]
