version: '3.9'

services:
  web:
    build: .
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/code
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
