services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    ports:
      - "8000:8000" 
    env_file:
      - .env
      

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  static_volume:
  media_volume: