services:
  web:
    build: .
    container_name: django_app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - backend

networks:
  backend:
    driver: bridge