# Generated by Django 5.0.7 on 2025-05-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='featured',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
