# Generated by Django 5.0.7 on 2025-05-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0002_featured_is_coming_soon_alter_featured_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
