# Generated by Django 5.0.7 on 2025-05-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0003_featured_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabipaycard',
            name='name_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tabipaycard',
            name='name_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tabipaycard',
            name='username_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tabipaycard',
            name='username_y',
            field=models.FloatField(null=True),
        ),
    ]
