# Generated by Django 5.0.7 on 2025-05-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0004_tabipaycard_name_x_tabipaycard_name_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabipaycard',
            name='name_font_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tabipaycard',
            name='username_font_size',
            field=models.FloatField(null=True),
        ),
    ]
