# Generated by Django 5.0.7 on 2025-05-18 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0005_tabipaycard_name_font_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeforgeFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='fonts/')),
            ],
        ),
        migrations.AlterField(
            model_name='tabipaycard',
            name='name_font_size',
            field=models.FloatField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='tabipaycard',
            name='name_x',
            field=models.FloatField(default=450, null=True),
        ),
        migrations.AlterField(
            model_name='tabipaycard',
            name='name_y',
            field=models.FloatField(default=850, null=True),
        ),
        migrations.AlterField(
            model_name='tabipaycard',
            name='username_font_size',
            field=models.FloatField(default=35, null=True),
        ),
        migrations.AlterField(
            model_name='tabipaycard',
            name='username_x',
            field=models.FloatField(default=450, null=True),
        ),
        migrations.AlterField(
            model_name='tabipaycard',
            name='username_y',
            field=models.FloatField(default=900, null=True),
        ),
        migrations.AddField(
            model_name='tabipaycard',
            name='font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='featured.memeforgefont'),
        ),
    ]
