# Generated by Django 5.0.7 on 2025-04-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vercel_blob_url', models.URLField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('x_post_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Submission',
                'verbose_name_plural': 'User Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
