# Generated by Django 5.0.7 on 2025-04-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='x_post_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
