# Generated by Django 5.0.7 on 2025-05-16 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_usersubmission_x_post_url'),
        ('users', '0003_alter_memeforgeuser_x_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='memeforge_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.memeforgeuser'),
        ),
    ]
