# Generated by Django 5.0.7 on 2025-05-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_usersubmission_memeforge_user'),
        ('users', '0004_alter_memeforgeuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='memeforge_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.memeforgeuser'),
        ),
    ]
